spring.application.name=veturno

spring.datasource.url=jdbc:mysql://localhost:3306/vetturno
spring.datasource.username=root
spring.datasource.password=Hk4653

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true